#!/usr/bin/env zsh

DOTFILES="$HOME/.dotfiles"
STOW_FOLDERS="nvim,zsh,bin,tmux,alacritty"

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder

    if [ $? -eq 0 ]; then
        echo "$folder linked successfully."
    else
        echo "$folder not linked."
    fi

done
popd

echo "Finished linking $DOTFILES"
