require('core.plugin_config.ayu')
require('core.plugin_config.lualine')
require('core.plugin_config.nvim-tree')
require('core.plugin_config.telescope')
require('core.plugin_config.treesitter')
require('core.plugin_config.lsp-config')
require('core.plugin_config.nvim-cmp')
require('core.plugin_config.git')
require('core.plugin_config.which-key')

